CREATE DATABASE IF NOT EXISTS qb;
CREATE DATABASE IF NOT EXISTS qb_test;
CREATE TABLE IF NOT EXISTS orders (
    order_id INT PRIMARY KEY,
    order_number VARCHAR(128),
    order_data  VARCHAR(4096),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS invoices (
	invoice_id INT PRIMARY KEY,
    order_id INT UNIQUE,
	INDEX ord_id (order_id),
    FOREIGN KEY (order_id)
		REFERENCES orders(order_id)
        ON DELETE CASCADE,    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS order_error (
	id INT auto_increment PRIMARY KEY,
    order_id INT,
    INDEX ord_id (order_id),
	FOREIGN KEY (order_id)
		REFERENCES orders(order_id)
        ON DELETE CASCADE,  
    err VARCHAR(4096),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS bill (
    bill_id INT PRIMARY KEY,
    bill_number VARCHAR(128),
    bill_data VARCHAR(4096),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS bill_references (
    ref_id INT  PRIMARY KEY,
    bill_id INT,
	INDEX b_id (bill_id),
    FOREIGN KEY (bill_id)
		REFERENCES bill(bill_id)
        ON DELETE CASCADE,    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS bill_error (
	id INT auto_increment PRIMARY KEY,
    bill_id INT,
    INDEX b_id (bill_id),
	FOREIGN KEY (bill_id)
		REFERENCES bill(bill_id)
        ON DELETE CASCADE,     
    err VARCHAR(4096),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=INNODB;